### ISSUE TITLE
www-apps/hugo build fails

### ISSUE THREAD

**Issue by scottfurry** [Dr-Terrible/go-overlay#2]
ebuild fails emerge as sources cannot be downloaded.
issue was tried on 0.15_pre\* and 0.14.

Log files cannot be attached as github does not support text files.
0.14 build log file - http://pastebin.com/trfz7pz8
0.15 pre build log - http://pastebin.com/55UnaSnc

**Comment by scottfurry** [comment]
I think I can see why the build is failing. The source tarball is not being grabbed.
The sources are available at ( https://github.com/spf13/hugo/archive/v0.14.tar.gz ). This path does not appear in the ebuild source.

**Comment by Dr-Terrible** [comment]
Thank you for the report @scottfurry.
From the log files you shared I can see that you have a problem with _tar_:

> tar: hugo-0.14: **Cannot mkdir: Permission denied**

Either you have a problem with your filesystem (disk full? wrong user permissions for /var/tmp/portage/ ?), or your tar command is not working correctly.

From the log I can see that you have reached the `unpack phase`, that means the tarballs have been correctly downloaded and `emerge` successfully verified their hashes. Otherwise `emerge` would have complained before to reach that point.

> I think I can see why the build is failing. The source tarball is not being grabbed. [...] This path does not appear in the ebuild source.

SRC_URIs are generated inside the eclass, not the ebuild. Keep in mind that GoLang packages are quite special and they have a complete different toolchain than standard C/C++ packages. The Go compiler reasons in terms of workspaces: https://golang.org/doc/code.html#Workspaces

However I can't reproduce your issue. I just tested by creating from scratch a Gentoo VM (amd64), synced the overlay, and `emerge` was able to download the tarballs and correctly compile them.

I'm not saying you are not having a problem, just that I don't understand it, so I need more info. Please, can you paste me your `emerge --info`? Which type of filesystem are you using for /var/tmp/portage ?

**Comment by scottfurry** [comment]
emerge --info here: http://pastebin.com/m1Ed1a2X
permissions? doubtful. permissions are setup correctly (775 portage portage)
disk full? not even at 50%
path spaces - got that. I looked at the URI's. May not be applicable.
I can build hugo from within go - seems counter intuitive to "distribution"
/var/tmp/portage FS is ext4

**Comment by scottfurry** [comment]
FTR:
dev-libs/go-fuse, dev-libs/go-usb and sys-fs/go-mtpfs are all dependent on dev-lang/go and are installed on my system. They did not present a similar problem when installing.

**Comment by Dr-Terrible** [comment]
> emerge --info here:

We have pretty much the same set up. The only difference is the hardware.

Here is the log of the test I have aforementioned in my previous comment: http://pastebin.com/G9Va6cnU
Do you notice something different that is happening on your machine?

Please, try to clean your /var/tmp/portage/\* and /usr/portage/distfiles/*, re-sync the overlay, and then re-emerge hugo.

> I can build hugo from within go - seems counter intuitive to "distribution"

Indeed, GoLang packages are not meant to be distributed by package mangers (it's by design); that is why I linked you the documentation about GoLang's workspaces. My overlay uses a special eclass to create a GoLang workspace inside the ebuild workdir (/var/tmp/portage/<pkg>/work/), extract all the dependencies and then build the binaries. That is why the ebuild is pretty much empty. All the logic is inside the eclass. Go compiler doesn't either have a `configure` or a `make` phase a-la autotools; instead there is a "buildall-suiteforyourself" compilation that take care of everything.

p.s.: as a side note, the moment you'll succeed with my overlay, you'll also get two 'hugo' binaries competing in the PATH. One installed by `go get` inside your workspace's GOPATH, and one in `/usr/bin/hugo` installed by portage. Be careful to not use the wrong one by accident ;)

**Comment by scottfurry** [comment]
First thing that jumps out at me is the USE="{test}". I had tried to enable that without success. I can see the braces are necessary.

I had removed the overlay and cleaned the portage to no avail.

I will retry the overlay and with the "{test}" change. Will report back details.

**Comment by Dr-Terrible** [comment]
> I had removed the overlay and cleaned the portage to no avail.
> I will retry the overlay and with the "{test}" change. Will report back details.

No need for that. Finally, I was able to reproduce your issue  ;)
Apparently, we have the same Gentoo set up, except for a specific FEATURES option: **userpriv**. That option is triggering the messages about _tar_ and _bad permissions_. It should not behave like that.

What ever is the culprit, I'm gonna fix it ASAP ;)

> First thing that jumps out at me is the USE="{test}". I had tried to enable that without success. I can see the braces are necessary.

USE flag `test` is special. If you need to enable it when invoking emerge by the command-line then you must use FEATURES, like this:

`$ FEATURES="test" emerge -av pkgname`

**Comment by Dr-Terrible** [comment]
As a temporarily workaround use:

`$ FEATURES="-userpriv" emerge -av www-apps/hugo`

**Comment by scottfurry** [comment]
I'll defer to you there...
Whatever I tried to enable "test" wouldn't work until I used "FEATURES=".
A build with 'FEATURES="test"' would still fail.

As soon as I did the workaround you suggested...done. Works.
I still have "{-test}" being reported, but hugo is built.

Hugo Static Site Generator v0.14 BuildDate: 2015-07-29T09:00:29-06:00
:-)

**Comment by scottfurry** [comment]
Okay...I have a bit of a workaround for now.
https://wiki.gentoo.org/wiki/Knowledge_Base:Overriding_environment_variables_per_package#Resolution

```
# mkdir -p /etc/portage/env
# echo 'FEATURES="${FEATURES} -userpriv test"' >> /etc/portage/env/golang
# echo "www-apps/hugo golang" >> /etc/portage/package.env
# emerge -av www-apps/hugo
```

This seems to work well without resorting to extra stuff on the cmd line w/ emerge.

**Comment by Dr-Terrible** [comment]
> This seems to work well without resorting to extra stuff on the cmd line w/ emerge.

Yeah, but that was meant just as a temporarily workaround for letting you emerge the package without waiting for my fix. Nothing else.

Right now, I'm fixing my overlay's eclass to be compliant with FEATURES="userpriv". The commit will be ready in the next 24 hours.

**Comment by scottfurry** [comment]
Confirmed fix. Thx for your time.

**Comment by Dr-Terrible** [comment]
You're welcome, Scott.
If you need some other utility/tool written in GoLang which isn't present in Portage, feel free to open an issue here.  ;)
