### ISSUE TITLE
[dev-util/go-tools] File collision with /usr/bin/bundle from dev-ruby/bundler

### ISSUE THREAD

**Issue by ganto** [Dr-Terrible/go-overlay#22]
When trying to install `dev-util/go-tools` from your overlay and having `dev-ruby/bundler` installed, emerge will abort with a file collision error:

```
>>> Installing (1 of 1) dev-util/go-tools-20151230::go-overlay
 * checking 21 files for package collisions
[...]
 * Detected file collision(s):
 *
 *      /usr/bin/bundle
 *
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 *
 * dev-ruby/bundler-1.10.6:0::gentoo
 *      /usr/bin/bundle
 * 
 * Package 'dev-util/go-tools-20151230' NOT merged due to file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.
```

Maybe you could rename it to something like `go-bundle`?

**Comment by Dr-Terrible** [comment]
> When trying to install dev-util/go-tools from your overlay and having dev-ruby/bundler installed, emerge will abort with a file collision error:

Oh. Nice catch! :octocat: 
Thank you for the report.

> Maybe you could rename it to something like go-bundle?

Or even better, the ebuild could install all the binaries inside `$GOROOT/bin` since `go-tools` is an official part of the golang toolchain and it's not a library (so there is not the risk to mess up with GOROOT system libraries).

I'll fix it ASAP.

**Comment by ganto** [comment]
Thanks a lot. Works for me now.
