### ISSUE TITLE
[app-shells/fzf] version bump to 0.17.0-2

### ISSUE THREAD

**Issue by alessandro-molari** [Dr-Terrible/go-overlay#65]
Version 0.17.0-2 is available in upstream.

It fixes various issues, including hanging problems.

Please version bump to latest version.

Thanks,
Alessandro

**Comment by alessandro-molari** [comment]
@Dr-Terrible Any updates?

**Comment by alessandro-molari** [comment]
The current version of fzf doesn't work anymore, with new go toolchain.

Is it possible to have a version dump?

Thanks,
Alessandro

**Comment by alessandro-molari** [comment]
@Dr-Terrible Any updates?

**Comment by aidanharris** [comment]
I've managed to build an ebuild here which might be useful:

https://gist.github.com/aidanharris/03ce326e1b06e3ced8897c55094a52cd

I don't yet fully understand what I've done and still need to read up more on ebuilds so won't submit this as a pull-request since it's likely not up to the standard of quality Gentoo expects. Here's the diff though if anyone's curious what I changed:

```diff
7,8c7
< GOLANG_PKG_BUILDPATH="/src/${PN}"
< GOLANG_PKG_TAGS="release"
---
> GOLANG_PKG_TAGS="${PV}"
12,19c11
< GOLANG_PKG_DEPENDENCIES=(
< 	"github.com/junegunn/go-isatty:66b8e73"
< 	"github.com/junegunn/go-runewidth:63c378b"
< 	"github.com/junegunn/go-shellwords:33bd8f1"
< 	"github.com/golang/crypto:854ae91 -> golang.org/x"
< )
< 
< inherit golang-single bash-completion-r1
---
> inherit golang-live bash-completion-r1
31c23
< 	golang-single_src_install
---
> 	golang-live_src_install
```

https://gist.github.com/740a48b3f66e01fbc0363a39b17d2454

**Comment by Dr-Terrible** [comment]
v0.17.1 is now available from the overlay.
