### ISSUE TITLE
External commands disallowed while sourcing ebuild

### ISSUE THREAD

**Issue by lord-re** [Dr-Terrible/go-overlay#66]
I added the go-overlay sometimes ago.
But now every operation throw many errors when it sources ebuilds : 

*   External commands disallowed while sourcing ebuild: date -u +%m-%d-%Y

**Comment by firegurafiku** [comment]
Let's have a look onto one of the files to blame, `syncthing/syncthing-0.11.26-r1.ebuild`. The error is caused by the following line (hard-wrapping is mine):

```
GOLANG_PKG_LDFLAGS="-w -X main.Version=v${PV} -X main.BuildUser=portage \
        -X main.BuildHost=gentoo -X main.BuildStamp=$( date +%s )"
```

Calling `date` here seems quite innocent, but is still an external command and forbidden according to EAPI 6 (despite that I have no idea how it's even detected by portage).

I can see only one way to fix it at the moment:

```
GOLANG_PKG_LDFLAGS="-w -X main.Version=v${PV} -X main.BuildUser=portage \
        -X main.BuildHost=gentoo"

src_compile() {
        GOLANG_PKG_LDFLAGS+="-X main.BuildStamp=$(date +%s)"
        golang-single_src_compile
        ...
}
```

Since all these errors we about various `date` usages, it may be worth adding `golang_getdate` or similar function to the profile itself.
