### ISSUE TITLE
[dev-go/gobot] ebuild request

### ISSUE THREAD

**Issue by holgersson32644** [Dr-Terrible/go-overlay#90]
Hi, could you write an ebuild for [gobot](https://gobot.io/), please?

I’ll attach my ebuild draft (which didn't work):

```
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6


EGO_PN="gobot.io/x/gobot/..."

inherit golang-build

DESCRIPTION="Golang Powered Robotics"
HOMEPAGE="https://gobot.io/ https://github.com/hybridgroup/gobot.git"
SRC_URI="https://github.com/hybridgroup/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}"
```

**Comment by Dr-Terrible** [comment]
> Hi, could you write an ebuild for gobot, please?

Sure, it could be done.

> I’ll attach my ebuild draft (which didn't work):

It doesn't work because you're using `golang-build` eclass, which is not supported by this overlay. I highly doubt `golang-build` can properly compile something like gobot.

However, I'm queuing up Gobot v1.9.0 ;)

**Comment by Dr-Terrible** [comment]
Just to point out the obvious: Gobot is a **framework**, not a Go standalone application.

Since it is just a library (you install it into your GOPATH with `go get -u -v gobot.io/x/gobot/...`) there is nothing that an `ebuild` can automate here; the only Gobot's component that can be compiled into an executable is the CLI, as explained [here](https://gobot.io/documentation/guides/cli/) — unless I'm mistaken and I'm missing something important from the online doc. That is trivial to do, and that is exactly what the ebuild I just pushed does: 401ccdcd433dbaa93335d1397766565205f1787b

Let me known if there are missing pieces from Gobot that you would like to be packaged (provided that they can be compiled into Go standalone applications).

p.s.: having Gobot's framework installed with `go get`  is not enough for running Gobot's components that require OpenCV; you need to have opencv libs installed by emerge, and then compile `gocv` as explained here: https://gobot.io/documentation/platforms/opencv  + https://gocv.io/getting-started/linux/

**Comment by holgersson32644** [comment]
That was pretty fast, thanks! Well, I’m completely new to go and tried to package something like the typical C libs, where the package contains some headers and libs (.so files).
It looks as this gobot binary incorporates all necessary files though. If not I’ll come back and complain ;)

PS: Thanks for the OpenCV hint (though I think won't need it).
